### ISSUE TITLE
User Pool Config - Can't reset passwords

### ISSUE THREAD

**Issue by gonwi** [awslabs/aws-api-gateway-developer-portal#323]
Hi,

After successfully deploying the app. Everything works just fine but the default cognito user configuration. Doesn't allow for email confirm or to reset passwords.

When trying reset the passwords I get.

> Could not reset password for the account, please contact support or try again

As I understand, you can't change cognito user pool attributes after a pool is created.

- Is there any option to change this before deployment, or make changes to the stack template after in order to fix?

- Does someone else encounter this problem?

Thanks

**Comment by rutabagaman** [comment]
I ran into something similar; basically Cognito is pretty brittle and won't let you change some basic UserPool properties after it's been created.  For instance you can't:
- change allowing users to sign in with email/phone number/preferred username
- update which attributes are required/optional
- delete custom attributes(though you can always add new ones)

In the Cognito documentation they basically advocate creating a new UserPool and creating a lambda function to migrate users from the old to the new.  Pretty clunky.  

If you're still playing with it in dev, you can delete the UserPool by first deleting the domain under App integration:Domain Name in the console, then delete the UserPool proper.  Once that's finished, you can kick off the CloudFormation deploy to re-create it.

**Comment by rutabagaman** [comment]
FYI, your CloudFormation YAML changes would look like this for UserPool to enable logging in with email with email confirmation:
`  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref CognitoIdentityPoolName
      AutoVerifiedAttributes:
        - email
      LambdaConfig:
        PreSignUp: !GetAtt CognitoUserPoolsConfirmationStrategyFunction.Arn
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: true
          RequireNumbers: true
      UsernameAttributes:
        - email`

**Comment by rutabagaman** [comment]
FYI, your cloudformation YAML would look something like this to configure the app for logging in with validated email addresses and forgot password enabled:

```
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref CognitoIdentityPoolName
      AutoVerifiedAttributes:
        - email
      LambdaConfig:
        PreSignUp: !GetAtt CognitoUserPoolsConfirmationStrategyFunction.Arn
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: true
          RequireNumbers: true
      UsernameAttributes:
        - email
```
